### ISSUE TITLE
No support for remote images on Android

### ISSUE THREAD

**Issue by Topener** [apra-informatica/Ti.ImageViewer#4]
I got the error remote images are not supported. Converting to blob and adding it after that works though...

Your example uses remote images, so not sure if it is a bug on my end or it really doesn't support it

**Comment by nonno** [comment]
The example about remote image in the readme isn't mine but of another guy. My fault, he did a pull request for a modification of the readme and I didn't check if it worked. Now I'm in holiday with only a smartphone, in one week I'll check.

**Comment by nonno** [comment]
You are right, the Android module doesn't work with remote images. I changed the readme, thanks.
